'use client'

import { AR } from '@/components'

const allowedChains: Record<string, string[]> = {
  solana: [
    'pumpswap',
    'raydium',
    'meteora',
    'orca',
    'launchlab',
    'pumpfun',
    'dexlab',
    'fluxbeam',
    'meteoradbc',
    'moonit',
    'coinchef',
    'vertigo',
    'tokenmill',
    'superx'
  ],
  ethereum: [
    'uniswap',
    'curve',
    'balancer',
    'pancakeswap',
    'solidlycom',
    'sushiswap',
    'fraxswap',
    'shibaswap',
    'ethervista',
    'defiswap',
    'verse',
    '9inch',
    'lif3',
    'stepn',
    'orion',
    'safemoonswap',
    'radioshack',
    'wagmi',
    'diamondswap',
    'empiredex',
    'swapr',
    'blueprint',
    'okxdex',
    'memebox',
    'kyberswap',
    'pyeswap',
    'templedao',
    'vulcandex'
  ],
  base: [
    'aerodrome',
    'uniswap',
    'pancakeswap',
    'baseswap',
    'alien-base',
    'sushiswap',
    'balancer',
    'deltaswap',
    'solidlycom',
    'swapbased',
    'dackieswap',
    'iziswap',
    'equalizer',
    'rocketswap',
    'infusion',
    '9mm',
    'shark-swap',
    'treble',
    'diamondswap',
    'velocimeter',
    'synthswap',
    'leetswap',
    'citadelswap',
    'basex',
    'robots-farm',
    'horizondex',
    'satori',
    'derpdex',
    'basofinance',
    'candy-swap',
    'cloudbase',
    'fwx',
    'throne',
    'memebox',
    'icecreamswap',
    'crescentswap',
    'moonbase',
    'kokonutswap',
    'lfgswap',
    'oasisswap',
    'degenbrains',
    'cbswap',
    'bakeryswap',
    'basedswap',
    'ethervista',
    'glacier'
  ],
  bsc: [
    'pancakeswap',
    'uniswap',
    'thena',
    'squadswap',
    'unchain-x',
    'biswap',
    'fstswap',
    'apeswap',
    'bakeryswap',
    'coinfair',
    'tiktokfun',
    'babyswap',
    'dinosaureggs',
    'sushiswap',
    'mdex',
    'babydogeswap',
    'orion',
    'nomiswap',
    'dexswap',
    'tidaldex',
    'openocean',
    'knightswap',
    'autoshark',
    'safemoonswap',
    'marsecosystem',
    'iziswap',
    'mochiswap',
    'planetfinance',
    'elkfinance',
    'w3swap',
    'swych',
    'jetswap',
    'hyperjump',
    'coneexchange',
    'fraxswap',
    'kyotoswap',
    'radioshack',
    'jswap',
    'baryonswap',
    'padswap',
    'traderjoe',
    'orbitalswap',
    'saitaswap',
    'sphynx',
    'pandora',
    'leonicorn',
    'annexfinance',
    'empiredex',
    'diamondswap',
    'pyreswap',
    'niob',
    'kyberswap',
    'pyeswap',
    'lif3',
    'ethervista',
    'aequinox',
    'vertek'
  ],
  pulsechain: [
    'pulsex',
    '9mm',
    '9inch',
    'pdex',
    'uniswap',
    'pulse-rate',
    'sushiswap',
    'sparkswap',
    'dextop',
    'eazyswap',
    'velocimeter'
  ],
  avalanche: [
    'pharaoh',
    'traderjoe',
    'arenatrade',
    'uniswap',
    'pangolin',
    'aquaspace',
    'kyberswap',
    'vapordex',
    'fraxswap',
    'hurricaneswap',
    'lydiafinance',
    'sushiswap',
    'radioshack',
    'swapsicle',
    'hakuswap',
    'elkfinance',
    'alligator',
    'yetiswap',
    'partyswap',
    'glacier',
    'thorus',
    'pyreswap',
    'fwx',
    'diamondswap',
    'onavax',
    'empiredex',
    'tokenmill'
  ],
  polygon: [
    'quickswap',
    'uniswap',
    'balancer',
    'sushiswap',
    'dooar',
    'retro',
    'apeswap',
    'dfyn',
    'vulcandex',
    'fraxswap',
    'polycat',
    'kyberswap',
    'jetswap',
    'polyzap',
    'gravityfinance',
    'mmfinance',
    'radioshack',
    'dinoswap',
    'dystopia',
    'comethswap',
    'nachofinance',
    'lif3',
    'elkfinance',
    'jamonswap',
    'pearl',
    'algebra',
    'firebird',
    'satin',
    'empiredex',
    'safemoonswap',
    'tetuswap'
  ],
  arbitrum: [
    'uniswap',
    'pancakeswap',
    'camelot',
    'ramses',
    'sushiswap',
    'traderjoe',
    'arbswap',
    'zyberswap',
    'spartadex',
    'deltaswap',
    'solidlycom',
    'fraxswap',
    'kyberswap',
    'swapr',
    'chronos',
    'mmfinance',
    'solidlizard',
    'magicswap',
    'elkfinance',
    'oreoswap',
    'arbidex',
    'swapfish',
    'aegis',
    'mindgames',
    'oasisswap',
    'auragi',
    'alienfi',
    'sharkyswap',
    'apeswap',
    'sterling',
    'dackieswap',
    '3xcalibur',
    'arbiswap',
    'degenbrains',
    'spinaqdex',
    'shekelswap',
    'ethervista',
    'crescentswap',
    'dexfi'
  ],
  optimism: [
    'velodrome',
    'uniswap',
    'solidlycom',
    'beethovenx',
    'sushiswap',
    'fraxswap',
    'zipswap',
    'kyberswap',
    'openxswap',
    'superswap',
    'elkfinance',
    'dackieswap'
  ],
  fantom: [
    'spookyswap',
    'wigoswap',
    'beethovenx',
    'spiritswap',
    'equalizer',
    'pyreswap',
    'velocimeter',
    'protofi',
    'morpheusswap',
    'hyperjump',
    'solidly',
    'tombswap',
    'sushiswap',
    'paintswap',
    'lif3',
    'solidlycom',
    'farmtom',
    'degenhaus',
    'redemption',
    'knightswap',
    'soulswap',
    'excalibur',
    'elkfinance',
    'yoshiexchange',
    'wingswap',
    'bombswap',
    'jetswap',
    'skullswap',
    'memebox',
    'defyswap',
    'kyberswap',
    'wagmi',
    'empiredex',
    'fraxswap'
  ],
  blast: [
    'thruster',
    'ring',
    'fenix',
    'blade',
    'uniswap',
    'ambient',
    'blaster',
    'monoswap',
    'roguex',
    'sushiswap',
    'swapblast',
    'cyberblast',
    'hyperblast',
    'diamondswap',
    'dyorswap',
    'bitdex',
    'dackieswap',
    'icecreamswap'
  ],
  zksync: [
    'pancakeswap',
    'syncswap',
    'zkswap',
    'oku',
    'spacefi',
    'koi',
    'iziswap',
    'velocore',
    'ezkalibur',
    'vesync',
    'gemswap',
    'wagmi',
    'derpdex',
    'draculafi',
    'holdstation',
    'gameswap'
  ],
  linea: [
    'lynex',
    'nile',
    'pancakeswap',
    'syncswap',
    'oku',
    'iziswap',
    'sushiswap',
    'horizondex',
    'secta',
    'echodex',
    'kyberswap',
    'metavault',
    'leetswap',
    'satori',
    'diamondswap',
    'velocore'
  ],
  scroll: [
    'nuri',
    'ambient',
    'syncswap',
    'oku',
    'iziswap',
    'sushiswap',
    'zebra',
    'skydrome',
    'spacefi',
    'kyberswap',
    'scribe',
    'punkswap',
    'scrollswap',
    'zada-finance',
    'tokan',
    'metavault',
    'papyrusswap',
    'icecreamswap',
    'luigiswap',
    'cattieswap',
    'leetswap'
  ],
  mantle: [
    'merchantmoe',
    'agni',
    'cleo',
    'fusionx',
    'methlab',
    'funny-money',
    'iziswap',
    'butter.xyz',
    'crust',
    'swapsicle',
    'velocimeter'
  ],
  mode: ['velodrome', 'kim', 'poolshark', 'swapmode', 'supswap', 'dyorswap', 'dackieswap'],
  manta: ['quickswap', 'pacificswap', 'aperture-swap', 'gullnetwork', 'iziswap', 'oku', 'firefly', 'cetoswap', 'leetswap'],
  gnosischain: ['sushiswap', 'honeyswap', 'swapr', 'elkfinance', 'baofinance'],
  celo: ['uniswap', 'velodrome', 'ubeswap', 'sushiswap'],
  moonbeam: [
    'solarflare',
    'stellaswap',
    'zenlink',
    'beamswap',
    'padswap',
    'lunardex',
    'sunflowerswap',
    'dustydunes',
    'thorus',
    'sushiswap'
  ],
  moonriver: ['solarbeam', 'sushiswap', 'huckleberry', 'zenlink', 'elkfinance', 'padswap', 'seadex'],
  harmony: [
    'sushiswap',
    'swap',
    'tranquilfinance',
    'defikingdoms',
    'viperswap',
    'openswap',
    'lootswap',
    'mochiswap',
    'hermesdefi',
    'foxswap',
    'wagmidao',
    'bossswap',
    'sonicswap',
    'elkfinance',
    'fuzzswap'
  ],
  metis: ['netswap', 'wagmi', 'hercules', 'tethys', 'uni-maia', 'hermesprotocol', 'sushiswap'],
  astar: ['arthswap', 'zenlink', 'versa', 'polkaex', 'astarexchange', 'agsfinance', 'funbeast'],
  aurora: ['trisolaris', 'auroraswap', 'wannaswap', 'nearpad', 'amaterasu', 'iziswap', 'mindgames', 'polaris'],
  evmos: ['forge', 'spacefi', 'evmoswap', 'cronusfinance', 'diffusion'],
  kava: ['wagmi', 'kinetix', 'equilibre', 'elkfinance', 'surfswap', 'photonswap'],
  telos: ['swapsicle', 'apeswap', 'elkfinance', 'icecreamswap', 'omnidex', 'sushiswap', 'zappy'],
  fuse: ['voltagefinance', 'elkfinance', 'sushiswap'],
  boba: ['oku', 'sushiswap', 'oolongswap'],
  opbnb: [
    'pancakeswap',
    'cubiswap',
    'thena',
    'derpdex',
    'binaryswap',
    'fourdex',
    'pixelswap',
    'luigiswap',
    'knightdex',
    'diamondswap',
    'leetswap',
    'udex'
  ],
  polygonzkevm: ['quickswap', 'pancakeswap', 'doveswap', 'sushiswap', 'leetswap'],
  arbitrumnova: ['sushiswap', 'arbswap', 'rcpswap'],
  iotex: ['mimo', 'elkfinance'],
  tron: ['sunswap'],
  ton: ['stonfi', 'dedust'],
  sui: ['bluefin', 'cetus', 'turbos-finance', 'aftermath', 'flowx', 'bluemove'],
  aptos: ['thala', 'cellana', 'liquidswap', 'pancakeswap', 'aux', 'animeswap'],
  starknet: ['ekubo', 'jediswap', 'nostra', 'sithswap'],
  osmosis: ['osmosis'],
  injective: ['dojoswap'],
  hyperliquid: ['hyperliquid'],
  xrpl: ['xrpl']
}

const PageDexApiSupported = (): JSX.Element => {
  const entries = Object.entries(allowedChains)

  return (
    <>
      <AR.Header>Supported Chains & DEXs</AR.Header>

      <AR.P>
        Daftar ini diambil dari konfigurasi backend (<code>allowedChains</code>) pada handler Go.
      </AR.P>

      <AR.H2>Trendingscore</AR.H2>

      <AR.UL>
        <li>
          <code>m5</code>
        </li>
        <li>
          <code>h1</code>
        </li>
        <li>
          <code>h6</code>
        </li>
        <li>
          <code>h24</code>
        </li>
      </AR.UL>

      <AR.H2>Supported DEXs by Chain</AR.H2>

      <AR.Table minWidth="56rem" className="not-prose">
        <AR.Row>
          <AR.Cell isHeader>Chain</AR.Cell>
          <AR.Cell isHeader>DEXs</AR.Cell>
        </AR.Row>
        {entries.map(([chain, dexs]) => (
          <AR.Row key={chain}>
            <AR.Cell className="shrink-0">
              <code>{chain}</code>
            </AR.Cell>
            <AR.Cell className="flex-1 whitespace-pre-wrap break-words">{dexs.join(', ')}</AR.Cell>
          </AR.Row>
        ))}
      </AR.Table>

      <AR.Navigation
        prevHref="/docs/developer/dex-api"
        prev="DEX API"
        nextHref="/docs/developer/dex-api/example-request"
        next="Example Request"
      />
    </>
  )
}

export { PageDexApiSupported }
